### ISSUE TITLE
Useless config/config.ex ?

### ISSUE THREAD

**Issue by conradfr** [MikaAK/request_cache_plug#15]
https://github.com/MikaAK/request_cache_plug/blob/main/config/config.ex

Is this file used? It seems even the atom is wrong:

`config :request_cache,` instead of `config :request_cache_plug,`

It's also wrong in the readme, section "Specifying Specific Caching Locations"

**Comment by MikaAK** [comment]
It provides defaults if anyone looks using `Application.get_env` however, sometimes this doesn't compile properly in libraries and so defaults are set in the `config.ex`
